import Head from "next/head";
import Header from "@/partials/Header";

export default function Home() {
  return (
    <>
      <Head>
        <title>Green-glass</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>green</h1>
        <Header />
      </main>
    </>
  );
}
