import Head from "next/head";
import Header from "@/partials/Header";
import FeaturesHome from "@/partials/FeaturesHome";
import Footer from "@/partials/Footer";
import HeroHome from "@/partials/HeroHome";
import PageIllustration from "@/partials/PageIllustration";
import Tabs from "@/partials/Tabs";
import Testimonials from "@/partials/Testimonials";
import Process from "@/partials/Process";

export default function Home() {
  return (
    <>
      <Head>
        <title>Green-glass</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main class="font-inter antialiased bg-gray-900 text-gray-200 tracking-tight">
        <Header />
        <HeroHome />
        <PageIllustration />
        <HeroHome />
        <Tabs />
        <Testimonials />
        <FeaturesHome />
        <Process />
        <Footer />
      </main>
    </>
  );
}
