import Head from "next/head";
import Header from "@/partials/Header";
import FeaturesHome from "@/partials/FeaturesHome";
import Footer from "@/partials/Footer";
import HeroHome from "@/partials/HeroHome";
import PageIllustration from "@/partials/PageIllustration";
import Tabs from "@/partials/Tabs";
import Testimonials from "@/partials/Testimonials";
import Process from "@/partials/Process";
import News from "@/partials/News";

export default function Home() {
  return (
    <>
      <Head>
        <title>Green-glass</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="grow">
        <div className="flex flex-col min-h-screen overflow-hidden">
          <Header />
          <HeroHome />
          <Process />
          <PageIllustration />
          <Tabs />
          <News />
          <Testimonials />
          <FeaturesHome />
          <Footer />
        </div>
      </main>
    </>
  );
}
